version: '3.8'
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
  ollama:
    hostname: ollama
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    depends_on:
      - app
