version: '3.8'
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      OLLAMA_API_URL: http://ollama:11434
    depends_on:
      - ollama
    networks:
      - mi-red-ia

  ollama:
    hostname: ollama
    container_name: ollama
    build: ./ollama
    ports:
      - "11434:11434"
    networks:
      - mi-red-ia
    # NUEVO: Añadimos un volumen para persistir los modelos descargados
    volumes:
      - ollama-data:/root/.ollama

networks:
  mi-red-ia:
    driver: bridge

# NUEVO: Define el volumen que usará el servicio ollama
volumes:
  ollama-data:
